service: serverless-typescript

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ap-southeast-1
  stage: dev

# functions:
#   - ${file(./resources/functions.yml)}

# resources:
#   - ${file(./resources/cognito.yml)}
#   - ${file(./resources/exports.yml)}

package:
  exclude:
    - "node_modules"

functions:
  hello:
    handler: handler.hello
