service: serverless-typescript

frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x
    architecture: arm64
    region: ap-southeast-1
    stage: dev
    logRetentionInDays: 30
    environment:
        LOG_LEVEL: ${self:custom.logLevel}

plugins:
    - serverless-offline
    - serverless-plugin-typescript
    - serverless-plugin-common-excludes
    - serverless-plugin-include-dependencies

functions:
    - ${file(./resources/functions.yml)}

custom:
    includeDependencies:
        enableCaching: true
    logLevelMap:
        prod: info
        staging: info
    logLevel: ${self:custom.logLevelMap.${sls:stage}, 'debug'}
